spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  jackson:
    deserialization:
      fail-on-unknown-properties: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  servlet:
    encoding:
      force: true