server:
  port: 8761 #eureka server port number
  servlet:
    encoding:
      force: true

spring:
  application:
    name: discoveryservice # eureka ?? ?? ID ??

eureka:
  client: #??? ????? ??
    register-with-eureka: false
    fetch-registry: false #??? true, ??? ??? ??? ??? ???? ???? ??? ?? ??? ??